# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: New Manifest for tool
  inputs:
    command: custom
    custom: 'new '
    arguments: tool-manifest

- task: DotNetCoreCLI@2
  displayName: Install EF Tool
  inputs:
    command: custom
    custom: 'tool '
    arguments: install dotnet-ef

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Create SQL Scripts
  inputs:
    command: custom
    custom: 'ef '
    arguments: migrations script --output $(Build.SourcesDirectory)/Sql/db_update.sql --idempotent  --startup-project "$(Build.SourcesDirectory)/src/Server/MasterCraft.Server.csproj" --project "$(Build.SourcesDirectory)/src/Infrastructure/MasterCraft.Infrastructure.csproj"

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish --os linux --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'src/Server/MasterCraft.Server.csproj'
    arguments: ' --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'publish artifacts'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: SqlScripts'
  inputs:
    PathtoPublish: $(Build.SourcesDirectory)/Sql/db_update.sql
    ArtifactName: SqlScripts
    FileCopyOptions:

- script: az login --service-principal --username 8b66bcaa-318d-4f9d-8c04-2b03b9caad7d --password pYk8Q~VW~w3OhmRjbVidBKSMcNtHAgzaZdtAVc6k --tenant 6ea9efe7-5b20-44a5-b7d2-f4994c74690d --allow-no-subscriptions
  displayName: 'Azure Login'

- script: az config set extension.use_dynamic_install=yes_without_prompt --debug
  displayName: 'Azure Config Setup'

- script: az postgres flexible-server execute --name mastercraft --admin-user mastercraftdevops --admin-password McDevops22! --database-name mastercraft --file-path $(Build.SourcesDirectory)/Sql/db_update.sql
  displayName: 'Run Update Scripts'